import Head from "next/head";
import React from "react";
import AllPost from "../../components/Post/AllPost";
const { request } = require("graphql-request");
export default function allPost({ posts }) {
  return (
    <div>
      <Head>
        <title>My blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Welcome to the CoderBlog</h1>
      <p>
        At CoderBlog, we bring you the latest in web development, programming
        tips, and tech trends. Dive into our expert articles, tutorials, and
        insights designed to help you enhance your coding skills. Whether you're
        a beginner or a seasoned developer, CoderBlog is your go-to resource for
        staying up-to-date and advancing your career.{" "}
      </p>
      <br />
      <h2>All posts</h2>
      <br />
      <AllPost posts={posts} />
    </div>
  );
}
export async function getStaticProps() {
  const endpoint = "http://127.0.0.1:1337/graphql";
  const query = `
  query {
    blogPosts {
      data {
        id
        attributes {
          title
          description
          slug
          content
          tags {
            data {
              attributes{
                name
              }
              
            }
          }
          author {
            data {
              attributes{
                  name
              }
            }
          }
          media {
            data {
              attributes {
                formats
              }
            }
          }
          createdAt
          updatedAt
          publishedAt
        }
      }
    }
  }
  `;

  const res = await request(endpoint, query);
  const posts = res.blogPosts.data;
  return {
    props: {
      posts: posts,
    },
  };
}
