import Head from "next/head";
import AllPost from "../../components/Post/AllPost";
import React from "react";
import axios from "axios";

export default function allPost({ posts }) {
  return (
    <div>
      <Head>
        <title>My blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Welcome to the CoderBlog</h1>
      <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin eu metus
        turpis. Cras posuere blandit erat, eu maximus erat rutrum ac. Aenean
        suscipit et ligula nec feugiat. Sed maximus purus nunc, ut sagittis
        neque placerat ac.{" "}
      </p>
      <br />
      <h2>All posts</h2>
      <br />
      <AllPost posts={posts} />
    </div>
  );
}
export async function getStaticProps() {
  const res = await axios.get("http://localhost:1337/api/blog-posts");
  const posts = res.data.data;
  return {
    props: {
      posts: posts,
    },
  };
}
