import Head from "next/head";
import LastestPost from "../components/Post/LastestPost";
// import axios from "axios";
import React from "react";
const { request } = require("graphql-request");
export default function Home({ posts }) {
  return (
    <div>
      <Head>
        <title>My blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Welcome to the CoderBlog</h1>
      <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin eu metus
        turpis. Cras posuere blandit erat, eu maximus erat rutrum ac. Aenean
        suscipit et ligula nec feugiat. Sed maximus purus nunc, ut sagittis
        neque placerat ac.{" "}
      </p>
      <br />
      <h2>Lastest posts</h2>
      <br />
      <LastestPost posts={posts} />
    </div>
  );
}
export async function getStaticProps() {
  const endpoint = "http://localhost:1337/graphql";
  const query = `
  query {
    blogPosts {
      data {
        id
        attributes {
          title
          description
          slug
          content
          tags {
            data {
              attributes{
                name
              }
              
            }
          }
          author {
            data {
              attributes{
                  name
              }
            }
          }
          media {
            data {
              attributes {
                formats
              }
            }
          }
          createdAt
          updatedAt
          publishedAt
        }
      }
    }
  }
  `;

  const res = await request(endpoint, query);
  const posts = res.blogPosts.data;
  return {
    props: {
      posts: posts,
    },
  };
}
