import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
export default function Home({ posts }) {
  return (
    <div>
      <Head>
        <title>My blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Welcome to the CoderBlog</h1>
      <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin eu metus
        turpis. Cras posuere blandit erat, eu maximus erat rutrum ac. Aenean
        suscipit et ligula nec feugiat. Sed maximus purus nunc, ut sagittis
        neque placerat ac.{" "}
      </p>
      <br />
      <h2>All posts</h2>
      <br />
      {posts &&
        posts.data.map((post, i) => (
          <Link key={i} href={post.attributes.urlSlug}>
            <div className="card">
              <h3>{post.attributes.title}</h3>
              <p>{post.attributes.description}</p>
            </div>
          </Link>
        ))}
    </div>
  );
}
export async function getStaticProps() {
  const res = await fetch("http://localhost:1337/api/blog-posts");
  const posts = await res.json();
  return {
    props: { posts },
  };
}
